US59_Biljana
ekilic76/Phoenix_Library pull request #11
Opened 2023-03-09 21:42 UTC by Biljana523

2023-03-09 23:54 UTC, latifetor requested changes
There are some conflict in loginPage 2 spots, and in the login.feature.  
Please correct your code with master branch

2023-03-10 01:49 UTC, latifetor requested changes
There are some conflict, please take a look

2023-03-10 03:35 UTC, erkine approved these changes

2023-03-10 04:47 UTC, closed without merging

2023-03-10 04:47 UTC, erkine commented
x